
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |p|
        p.name = "srv-ubuntu"
        p.memory = 1024
        p.cpus = 1
  end
  config.vm.hostname = "srv-ubuntu"
  config.vm.hostname = "srv-ubuntu.local"
  config.vm.network "public_network", ip: "192.168.0.51", bridge: "enp34s0"
  
  
  config.vm.provision "shell", inline: <<-SHELL
   apt-get update
   apt-get install net-tools -y
   apt-get intall vim -y
  SHELL
end
