
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |p|
        p.name = "srv-centos7"
        p.memory = 1024
        p.cpus = 1 
  end
  config.vm.hostname = "centos7"
  config.vm.hostname = "srv-centos7.local"
  config.vm.network "public_network", ip: "192.168.0.50", bridge: "enp34s0"

   config.vm.provision "shell", inline: <<-SHELL
     yum install update -y
     yum install vim -y
     yum install net-tools -y
   SHELL
end
